'use client';

import { createClient } from '@/utils/supabase/client';

export async function updateProfile(data: {
    date_of_birth?: string;
    country_of_residence?: string;
}) {
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) throw new Error('Unauthorized');

    const { error } = await supabase
        .from('profiles')
        .update({
            ...data,
            updated_at: new Date().toISOString()
        })
        .eq('id', user.id);

    if (error) {
        console.error('Error updating profile:', error);
        throw new Error(error.message);
    }

    return { success: true };
}

/**
 * Ensures the user has a valid student ID. If missing or invalid format,
 * it will be regenerated by the DB trigger on profile update.
 */
export async function ensureStudentId() {
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) throw new Error('Unauthorized');

    const { data: profile } = await supabase
        .from('profiles')
        .select('student_id')
        .eq('id', user.id)
        .single();

    const isValidStudentId = (id: string | undefined) => {
        return !!id && id.startsWith('HU') && id.length === 9;
    };

    if (!isValidStudentId(profile?.student_id)) {
        const { error } = await supabase
            .from('profiles')
            .update({ updated_at: new Date().toISOString() })
            .eq('id', user.id);

        if (error) throw error;

        const { data: updatedProfile } = await supabase
            .from('profiles')
            .select('student_id')
            .eq('id', user.id)
            .single();

        return { studentId: updatedProfile?.student_id };
    }

    return { studentId: profile.student_id };
}
